#############################################################################
# Makefile for building: SuperCoin-qt
# Generated by qmake (2.01a) (Qt 4.8.6) on: Thu Dec 11 16:45:38 2014
# Project:  SuperCoin-qt.pro
# Template: app
# Command: c:\Qt\4.8.6\bin\qmake.exe -spec ..\Qt\4.8.6\mkspecs\win32-g++-4.6 -o Makefile SuperCoin-qt.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = c:\Qt\4.8.6\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: SuperCoin-qt.pro  ../Qt/4.8.6/mkspecs/win32-g++-4.6/qmake.conf ../Qt/4.8.6/mkspecs/features/device_config.prf \
		../Qt/4.8.6/mkspecs/qconfig.pri \
		../Qt/4.8.6/mkspecs/features/qt_functions.prf \
		../Qt/4.8.6/mkspecs/features/qt_config.prf \
		../Qt/4.8.6/mkspecs/win32-g++/qmake.conf \
		../Qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		../Qt/4.8.6/mkspecs/features/default_pre.prf \
		../Qt/4.8.6/mkspecs/features/win32/default_pre.prf \
		../Qt/4.8.6/mkspecs/features/release.prf \
		../